
// All Characters
const GET_ALL_CHARACTER_INFO_REQUEST = 'GET_ALL_CHARACTER_INFO_REQUEST';
const GET_ALL_CHARACTER_INFO_REQUEST_SUCCESS = 'GET_ALL_CHARACTER_INFO_REQUEST_SUCCESS';
const GET_ALL_CHARACTER_INFO_REQUEST_FAILURE = 'GET_ALL_CHARACTER_INFO_REQUEST_FAILURE';

// One character
const GET_CHARACTER_INFO_REQUEST = 'GET_CHARACTER_INFO_REQUEST';
const GET_CHARACTER_INFO_REQUEST_SUCCESS = 'GET_CHARACTER_INFO_REQUEST_SUCCESS';
const GET_CHARACTER_INFO_REQUEST_FAILURE = 'GET_CHARACTER_INFO_REQUEST_FAILURE';

export {
  GET_ALL_CHARACTER_INFO_REQUEST,
  GET_ALL_CHARACTER_INFO_REQUEST_SUCCESS,
  GET_ALL_CHARACTER_INFO_REQUEST_FAILURE,
  GET_CHARACTER_INFO_REQUEST,
  GET_CHARACTER_INFO_REQUEST_SUCCESS,
  GET_CHARACTER_INFO_REQUEST_FAILURE
};

