const GET_CHARACTERS_INFO_REQUEST = 'character/GET_CHARACTERS_INFO_REQUEST';
const GET_CHARACTERS_INFO_REQUEST_SUCCESS =
  'character/GET_CHARACTERS_INFO_REQUEST_SUCCESS';
const GET_CHARACTERS_INFO_REQUEST_FAILURE =
  'character/GET_CHARACTERS_INFO_REQUEST_FAILURE';

export {
  GET_CHARACTERS_INFO_REQUEST,
  GET_CHARACTERS_INFO_REQUEST_SUCCESS,
  GET_CHARACTERS_INFO_REQUEST_FAILURE,
};
